<testsuites>
  <testsuite name="Finaktiva Creditos Digitales">
    <testcase classname="k" name="Registro" time="137737048.773">
      <failure message="The string [False] is not contained in [Validación Fallida: No se realizo login con el usuario asignado], while running the action [Aserciones.AsercionUsuario]" type="ERROR">The string [False] is not contained in [Validación Fallida: No se realizo login con el usuario asignado], while running the action [Aserciones.AsercionUsuario], running the action [Aserciones.AsercionUsuario]</failure>
    </testcase>
    <testcase classname="k" name="Registro" time="137882202.976" />
    <testcase classname="k" name="Registro" time="138026870.369">
      <failure message="Validación Fallida: No se realizo login con el usuario asignado" type="ERROR">Validación Fallida: No se realizo login con el usuario asignado, running the action [Aserciones.AsercionUsuario]</failure>
    </testcase>
    <testcase classname="k" name="Registro" time="138238663.471" />
    <testcase classname="k" name="Registro" time="138716447.114">
      <failure message="Validación Fallida: No se realizo login con el usuario asignado" type="ERROR">Validación Fallida: No se realizo login con el usuario asignado, running the action [Aserciones.AsercionUsuario]</failure>
    </testcase>
    <testcase classname="k" name="Registro" time="138904728.639">
      <failure message="Validación Fallida: No se realizo login con el usuario asignado" type="ERROR">Validación Fallida: No se realizo login con el usuario asignado, running the action [Aserciones.AsercionUsuario]</failure>
    </testcase>
    <testcase classname="k" name="Registro" time="13906816.159" />
    <testcase classname="k" name="Registro" time="142109184.537" />
    <testcase classname="k" name="Registro" time="142327351.942">
      <failure message="Validación Fallida: No se realizo login con el usuario asignado" type="ERROR">Validación Fallida: No se realizo login con el usuario asignado, running the action [Aserciones.AsercionUsuario]</failure>
    </testcase>
    <testcase classname="k" name="Registro" time="142508112.731">
      <failure message="Validación Fallida: No se realizo login con el usuario asignado" type="ERROR">Validación Fallida: No se realizo login con el usuario asignado, running the action [Aserciones.AsercionUsuario]</failure>
    </testcase>
  </testsuite>
</testsuites>